### PR TITLE
Fix that the selected list / suggestion items are unreadable

### PR DESCRIPTION
**Pull request by gnvk**
Since the latest update the default background selected line in the the suggest widgets makes it unreadable, as seen in this picture:
Screenshot 2021-06-15 at 9 36 14

I changed it to #c8e1ff which matches the "editorBracketMatch.border":
Screenshot 2021-06-15 at 9 37 09

Please feel free to pick any other colour, just make sure it's readable. Thanks!

### CODE REVIEW

**Comment by robsontenorio** [comment]
@gnvk 

Do you know how to fix that "CTRL+P" search?

The matched word  "css" is also blue, so selected line.

image

**Comment by robsontenorio** [comment]
Got it

```
            "list.activeSelectionBackground": "#bec8e7",

```

image

**Comment by gnvk** [comment]
I think fixing the foreground instead is a better solution.

Screenshot 2021-06-16 at 9 11 40

**Comment by robsontenorio** [comment]
Yes, it is about preference. Because you don’t have the highlighted chars.

**Comment by anabellaspinelli** [comment]
Hey! Is there anything I can help with to unblock this merge?

I love the theme but this color problem is becoming really annoying during development 😢

**Comment by gnvk** [comment]
> Hey! Is there anything I can help with to unblock this merge?
> 
> I love the theme but this color problem is becoming really annoying during development 😢

Until it gets merged by @thenikso you can fix it only for yourself by adding these to your settings.json:
```json
  "workbench.colorCustomizations": {
    "[GitHub Plus]": {
      "editorSuggestWidget.selectedForeground": "#c8e1ff",
      "list.focusHighlightForeground": "#c8e1ff"
    }
  },
```

**Comment by gnvk** [comment]
Closing this, because the issue was fixed by https://github.com/thenikso/github-plus-theme/commit/243ab632bb98f93f5267aa643928fe0c25bdd24f

**Pull request closed without merging**
